Repository AnimatiWA/AnimatiApp, pull requests merged in 2024-10, with the labels that each got.

#54 Uriel rochetti
  AnimatiApp Django/AnimatiBack/.gitignore
  AnimatiApp Django/AnimatiBack/AnimatiApp/migrations/0001_initial.py
  AnimatiApp Django/AnimatiBack/AnimatiApp/urls.py
  AnimatiApp Django/AnimatiBack/AnimatiApp/views.py
  AnimatiApp Django/AnimatiBack/AnimatiCrud/settings.py
  AnimatiApp Django/AnimatiBack/Procfile
  AnimatiApp Django/AnimatiBack/requirements.txt
  AnimatiApp Django/AnimatiBack/static/.gitkeep
Labels: SPRINT 2

#67 Se agrega permiso para acceder a internet
  AnimatiApp Android/app/src/main/AndroidManifest.xml
Labels: SPRINT 2

#64 Correciones ID clases java. Agrego OrderTracking.
  AnimatiApp Android/app/src/main/java/com/example/animatiappandroid/ForgotPasswordActivity.java
  AnimatiApp Android/app/src/main/java/com/example/animatiappandroid/OrderTrackingActivity.java
  AnimatiApp Android/app/src/main/java/com/example/animatiappandroid/ProfileActivity.java
  AnimatiApp Android/app/src/main/res/layout/activity_profile.xml
Labels: SPRINT 2

#78 Se agrega conexion al back a la vista de Carrito
  AnimatiApp Android/.idea/.gitignore
  AnimatiApp Android/.idea/compiler.xml
  AnimatiApp Android/.idea/deploymentTargetSelector.xml
  AnimatiApp Android/.idea/misc.xml
  AnimatiApp Android/app/.idea/gradle.xml
  AnimatiApp Android/app/.idea/misc.xml
  AnimatiApp Android/app/build.gradle
  AnimatiApp Android/app/src/main/java/com/example/animatiappandroid/Cart.java
  AnimatiApp Android/app/src/main/java/com/example/animatiappandroid/CartActivity.java
  AnimatiApp Android/app/src/main/java/com/example/animatiappandroid/Product.java
  AnimatiApp Android/app/src/main/java/com/example/animatiappandroid/ProductListAdapter.java
  AnimatiApp Android/app/src/main/res/layout/activity_cart.xml
  AnimatiApp Android/app/src/main/res/layout/cart_product_item_list.xml
Labels: SPRINT 2

#70 ForgotPassword
  AnimatiApp Android/.idea/gradle.xml
  AnimatiApp Android/app/src/main/java/com/example/animatiappandroid/ForgotPasswordActivity.java
  AnimatiApp Android/app/src/main/java/com/example/animatiappandroid/ProfileActivity.java
  AnimatiApp Android/app/src/main/res/drawable/button_border.xml
  AnimatiApp Android/app/src/main/res/layout/activity_profile.xml
  AnimatiApp Android/app/src/main/res/values/strings.xml
  AnimatiApp Django/AnimatiBack/AnimatiApp/urls.py
  AnimatiApp Django/AnimatiBack/AnimatiApp/views.py
  AnimatiApp Django/AnimatiBack/AnimatiCrud/settings.py
Labels: Pull Request

#79 Agrego todo .idea al .gitignore porque me tiene seco
  AnimatiApp Android/.gitignore
  AnimatiApp Android/.idea/.gitignore
  AnimatiApp Android/.idea/AnimatiApp Android.iml
  AnimatiApp Android/.idea/appInsightsSettings.xml
  AnimatiApp Android/.idea/assetWizardSettings.xml
  AnimatiApp Android/.idea/compiler.xml
  AnimatiApp Android/.idea/deploymentTargetSelector.xml
  AnimatiApp Android/.idea/gradle.xml
  AnimatiApp Android/.idea/migrations.xml
  AnimatiApp Android/.idea/misc.xml
  AnimatiApp Android/.idea/runConfigurations.xml
  AnimatiApp Android/.idea/vcs.xml
  AnimatiApp Android/app/.idea/.gitignore
  AnimatiApp Android/app/.idea/app.iml
  AnimatiApp Android/app/.idea/caches/deviceStreaming.xml
  AnimatiApp Android/app/.idea/gradle.xml
  AnimatiApp Android/app/.idea/migrations.xml
  AnimatiApp Android/app/.idea/misc.xml
  AnimatiApp Android/app/.idea/modules.xml
  AnimatiApp Android/app/.idea/other.xml
  AnimatiApp Android/app/.idea/vcs.xml
Labels: SPRINT 2

#82 Se borran comentarios innescesarios
  AnimatiApp Android/app/src/main/java/com/example/animatiappandroid/CartActivity.java
Labels: SPRINT 2

#84 Conexión entre la Gallery y el Carrito. Modificación en línea de código del Login.
  AnimatiApp Android/.idea/studiobot.xml
  AnimatiApp Android/app/build.gradle
  AnimatiApp Android/app/src/main/java/com/example/animatiappandroid/Cart.java
  AnimatiApp Android/app/src/main/java/com/example/animatiappandroid/Gallery.java
  AnimatiApp Android/app/src/main/java/com/example/animatiappandroid/LoginActivity.java
  AnimatiApp Android/app/src/main/java/com/example/animatiappandroid/ProductAdapter.java
  AnimatiApp Android/app/src/main/res/drawable/item_divider.xml
  AnimatiApp Android/app/src/main/res/layout/activity_gallery.xml
  AnimatiApp Android/app/src/main/res/layout/gallery.xml
  AnimatiApp Android/app/src/main/res/layout/gallery_item.xml
  AnimatiApp Android/app/src/main/res/layout/header.xml
  AnimatiApp Android/app/src/main/res/menu/main_menu.xml
  AnimatiApp Android/app/src/main/res/values/strings.xml
Labels: SPRINT 2

#88 Correcciones de ultimo momento
  AnimatiApp Android/app/src/main/java/com/example/animatiappandroid/Gallery.java
  AnimatiApp Android/app/src/main/java/com/example/animatiappandroid/LoginActivity.java
Labels: SPRINT 2

#89 Merge a main de Develop
  AnimatiApp Android/app/src/main/java/com/example/animatiappandroid/Gallery.java
  AnimatiApp Android/app/src/main/java/com/example/animatiappandroid/LoginActivity.java
  AnimatiApp Android/app/src/main/java/com/example/animatiappandroid/activity_inicio.java
  AnimatiApp Android/app/src/main/res/layout/activity_inicio.xml
Labels: SPRINT 2

#91 Se agrega endpoint de contacto. Se actualizan los archivos de migracion
  AnimatiApp Django/AnimatiBack/AnimatiApp/migrations/0002_correocontacto.py
  AnimatiApp Django/AnimatiBack/AnimatiApp/models.py
  AnimatiApp Django/AnimatiBack/AnimatiApp/serializers.py
  AnimatiApp Django/AnimatiBack/AnimatiApp/urls.py
  AnimatiApp Django/AnimatiBack/AnimatiApp/views.py
  AnimatiApp Django/AnimatiBack/AnimatiCrud/settings.py
Labels: SPRINT 2

#92 Uriel rochetti
  AnimatiApp Android/app/src/main/java/com/example/animatiappandroid/CartActivity.java
  AnimatiApp Android/app/src/main/java/com/example/animatiappandroid/LoginActivity.java
  AnimatiApp Django/AnimatiBack/AnimatiApp/serializers.py
  AnimatiApp Django/AnimatiBack/AnimatiApp/views.py
  AnimatiApp Django/AnimatiBack/AnimatiCrud/settings.py
Labels: SPRINT 2

#93 Develop
  AnimatiApp Android/app/src/main/java/com/example/animatiappandroid/CartActivity.java
  AnimatiApp Android/app/src/main/java/com/example/animatiappandroid/LoginActivity.java
  AnimatiApp Django/AnimatiBack/AnimatiApp/migrations/0002_correocontacto.py
  AnimatiApp Django/AnimatiBack/AnimatiApp/models.py
  AnimatiApp Django/AnimatiBack/AnimatiApp/serializers.py
  AnimatiApp Django/AnimatiBack/AnimatiApp/urls.py
  AnimatiApp Django/AnimatiBack/AnimatiApp/views.py
  AnimatiApp Django/AnimatiBack/AnimatiCrud/settings.py
Labels: SPRINT 2

#96 Se agrega peticion al endpoint de contacto en la vista de contacto de…
  AnimatiApp Android/app/src/main/java/com/example/animatiappandroid/ContactoActivity.java
  AnimatiApp Android/app/src/main/res/layout/activity_contacto.xml
Labels: SPRINT 2

#97 Se actualiza Develop
  AnimatiApp Android/app/src/main/res/layout/activity_contacto.xml
Labels: SPRINT 2

#100 Modificaciones vista RecoveryPassword / Limpieza de líneas de código en back no funcionales vinculadas.
  AnimatiApp Android/app/src/main/AndroidManifest.xml
  AnimatiApp Android/app/src/main/java/com/example/animatiappandroid/ForgotPasswordActivity.java
  AnimatiApp Android/app/src/main/java/com/example/animatiappandroid/RecoveryPasswordActivity.java
  AnimatiApp Android/app/src/main/res/layout/activity_recovery_password.xml
  AnimatiApp Android/app/src/main/res/values/strings.xml
  AnimatiApp Django/AnimatiBack/AnimatiApp/serializers.py
  AnimatiApp Django/AnimatiBack/AnimatiApp/views.py
Labels: bug

#101 Hotfix - recovery password
  AnimatiApp Android/app/src/main/AndroidManifest.xml
  AnimatiApp Android/app/src/main/java/com/example/animatiappandroid/ForgotPasswordActivity.java
  AnimatiApp Android/app/src/main/java/com/example/animatiappandroid/RecoveryPasswordActivity.java
  AnimatiApp Android/app/src/main/res/layout/activity_recovery_password.xml
  AnimatiApp Android/app/src/main/res/values/strings.xml
  AnimatiApp Django/AnimatiBack/AnimatiApp/serializers.py
  AnimatiApp Django/AnimatiBack/AnimatiApp/views.py
Labels: SPRINT 2
