Repository AnimatiWA/AnimatiApp, pull requests merged in 2024-11, with the labels that each got.

#119 Se implementa stock
  AnimatiApp Android/app/src/main/java/com/example/animatiappandroid/CartActivity.java
  AnimatiApp Android/app/src/main/java/com/example/animatiappandroid/Gallery.java
  AnimatiApp Android/app/src/main/java/com/example/animatiappandroid/Product.java
  AnimatiApp Android/app/src/main/java/com/example/animatiappandroid/ProductAdapter.java
  AnimatiApp Android/app/src/main/res/layout/gallery_item.xml
  AnimatiApp Django/AnimatiBack/AnimatiApp/migrations/0003_carrito_is_active.py
  AnimatiApp Django/AnimatiBack/AnimatiApp/models.py
  AnimatiApp Django/AnimatiBack/AnimatiApp/views.py
Labels: Correcciones para la defensa

#115 Funcionalidad "Mis datos" para ingreso a Profile.
  AnimatiApp Android/app/src/main/AndroidManifest.xml
  AnimatiApp Android/app/src/main/java/com/example/animatiappandroid/RecoveryPasswordActivity.java
  AnimatiApp Android/app/src/main/java/com/example/animatiappandroid/activity_inicio.java
  AnimatiApp Android/app/src/main/res/drawable/rect_button_background.xml
  AnimatiApp Android/app/src/main/res/layout/activity_inicio.xml
  AnimatiApp Android/app/src/main/res/values/strings.xml
Labels: Correcciones para la defensa

#121 Se agregan funcionalidad para agregar mas de 1 elemento al carrito. S…
  AnimatiApp Android/app/src/main/AndroidManifest.xml
  AnimatiApp Android/app/src/main/java/com/example/animatiappandroid/Gallery.java
  AnimatiApp Android/app/src/main/java/com/example/animatiappandroid/ProductAdapter.java
  AnimatiApp Android/app/src/main/res/layout/gallery_item.xml
  AnimatiApp Android/app/src/main/res/values/colors.xml
  AnimatiApp Android/app/src/main/res/values/strings.xml
Labels: Pull Request, Correcciones para la defensa

#122 Se visibiliza button en Login: "Olvidaste Contraseña?".
  AnimatiApp Android/app/src/main/res/layout/activity_login.xml
Labels: bug, Correcciones para la defensa

#123 Funcionalidad de borrar una unidad del carrito
  AnimatiApp Android/app/src/main/java/com/example/animatiappandroid/CartActivity.java
  AnimatiApp Android/app/src/main/java/com/example/animatiappandroid/Product.java
  AnimatiApp Android/app/src/main/java/com/example/animatiappandroid/ProductListAdapter.java
  AnimatiApp Android/app/src/main/res/layout/cart_product_item_list.xml
  AnimatiApp Android/app/src/main/res/values/strings.xml
  AnimatiApp Django/AnimatiBack/AnimatiApp/urls.py
  AnimatiApp Django/AnimatiBack/AnimatiApp/views.py
Labels: Pull Request, Correcciones para la defensa

#126 Se agrega endpoint para obtener historial de compras del usuario
  AnimatiApp Django/AnimatiBack/AnimatiApp/urls.py
  AnimatiApp Django/AnimatiBack/AnimatiApp/views.py
Labels: Pull Request, Correcciones para la defensa

#124 Cambio aspecto visual recuperación pass y cambio pass.
  AnimatiApp Android/app/src/main/res/layout/activity_forgot_pass_email.xml
  AnimatiApp Android/app/src/main/res/layout/activity_recovery_password.xml
  AnimatiApp Android/app/src/main/res/values/colors.xml
  AnimatiApp Android/app/src/main/res/values/strings.xml
Labels: Correcciones para la defensa

#128 Se revierten cambios
  AnimatiApp Android/app/src/main/res/layout/activity_forgot_pass_email.xml
  AnimatiApp Android/app/src/main/res/layout/activity_recovery_password.xml
Labels: Pull Request, Correcciones para la defensa

#129 Se vuelve a agregar endpoint que se borro
  AnimatiApp Django/AnimatiBack/AnimatiApp/urls.py
Labels: Pull Request, Correcciones para la defensa
